package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import java.util.Map;
import java.util.Set;

/* compiled from: com.google.android.gms:play-services-ads@@19.0.1 */
final class zzbif extends zzcsx {
    private zzeew<Context> zzelm;
    private zzeew<zzcum> zzemj;
    private final /* synthetic */ zzbhf zzene;
    private zzeew<String> zzeqp;
    private zzeew<zzdfn> zzeqq;
    private zzeew<zzawc> zzeqr;
    private zzeew<zzdeu> zzeqs;
    private zzeew<zzavq> zzeqt;
    private zzeew<zzbop> zzequ;
    private zzeew<Context> zzeqv;
    private zzeew<String> zzeqw;
    private zzeew<String> zzeqx;
    private zzeew<zzsn> zzeqy;
    private zzeew<zzdcu> zzeqz;
    private zzeew<zzawh> zzerc;
    private zzeew<zzcgq> zzerf;
    private zzeew<zzchm> zzeri;
    private zzeew<zzclk> zzerm;
    private zzeew<zzcge> zzern;
    private zzeew<zzcge> zzero;
    private zzeew<Map<zzdig, zzcge>> zzerp;
    private zzeew<zzcgc> zzerq;
    private zzeew<Set<zzbuv<zzdil>>> zzerr;
    private zzeew zzers;
    private zzeew<zzcgs> zzert;
    private zzeew<zzbuv<zzdil>> zzeru;
    private zzeew<Set<zzbuv<zzdil>>> zzerv;
    private zzeew<zzclp> zzerw;
    private zzeew<zzbuv<zzdil>> zzerx;
    private zzeew<Set<zzbuv<zzdil>>> zzery;
    private zzeew zzerz;
    private zzeew<zzdif> zzesa;
    private zzeew<zzdfj> zzesd;
    private zzeew<ApplicationInfo> zzesj;
    private zzeew<PackageInfo> zzesk;
    private zzeew<zzdof<String>> zzesl;
    private zzeew<String> zzesm;
    private zzeew<zzcty> zzesn;
    private zzeew<zzctp> zzeso;
    private zzeew<zzcwo> zzesp;
    private zzeew<zzcvp> zzest;
    private zzeew<zzcww> zzesu;
    private zzeew zzesv;
    private zzeew<Bundle> zzesw;
    private zzeew<zzcud> zzesx;
    private zzeew<zzcvj> zzesy;
    private zzeew<zzcwr> zzesz;
    private zzeew<zzcxc> zzeta;
    private zzeew<zzcxu> zzetb;
    private zzeew<zzcuw> zzetc;
    private zzeew<zzcxp> zzetd;
    private zzeew<zzdof<String>> zzete;
    private zzeew<zzctr> zzetf;
    private zzeew<zzcvx> zzetg;
    private zzeew<zzcyo> zzeth;
    private zzeew<zzcxl> zzeti;
    private zzeew<zzcvt> zzetj;
    private zzeew<zzcwb> zzetk;
    private zzeew<zzcxg> zzetl;
    private zzeew<zzcui> zzetm;
    private zzeew<zzcro> zzetn;
    private zzeew<zzcuq> zzeto;
    private zzeew<zzcxa> zzetp;
    private zzeew<zzcxv> zzetq;
    private zzeew<zzcvb> zzets;
    private zzeew<Set<zzcye<? extends zzcyb<Bundle>>>> zzetu;
    private zzeew<zzcyd<Bundle>> zzetv;
    private zzeew<zzbpm> zzetw;
    private zzeew<Integer> zzfcj;
    private zzeew<zzcjk> zzfck;
    private zzeew<zzcti> zzfcl;
    private zzeew<Set<String>> zzfcm;
    private zzeew<String> zzfcn;
    private zzeew<zzdby> zzfco;
    private zzeew<zzdof<zzctj>> zzfcp;

    private zzbif(zzbhf zzbhf, zzcta zzcta, zzbog zzbog, zzchc zzchc, zzbpt zzbpt, zzdfp zzdfp, zzdcu zzdcu, zzdby zzdby) {
        zzcta zzcta2 = zzcta;
        zzbpt zzbpt2 = zzbpt;
        zzdfp zzdfp2 = zzdfp;
        this.zzene = zzbhf;
        this.zzeqp = zzbpu.zzg(zzbpt);
        this.zzeqq = zzeek.zzaq(zzdfr.zza(zzdfp2, this.zzene.zzeme, this.zzeqp));
        this.zzeqv = zzdfu.zzc(zzdfp2, this.zzeqq);
        this.zzeqw = zzcit.zzac(this.zzeqv);
        this.zzfcj = zzeek.zzaq(new zzcte(zzcta));
        this.zzeqx = zzeek.zzaq(zzciv.zzanp());
        this.zzeqy = zzeek.zzaq(zzcfd.zze(this.zzene.zzelm, this.zzeqw, this.zzene.zzeln, this.zzfcj, this.zzeqx));
        this.zzern = zzeek.zzaq(zzcfi.zzamm());
        this.zzero = zzeek.zzaq(zzcfk.zzamn());
        this.zzerp = ((zzeen) ((zzeen) zzeel.zzhm(2).zza(zzdig.SIGNALS, this.zzern)).zza(zzdig.RENDERER, this.zzero)).zzbgn();
        this.zzerq = zzcgh.zzaa(this.zzeqy, this.zzerp);
        this.zzerr = zzeek.zzaq(zzcfm.zzy(zzdhi.zzasq(), this.zzerq));
        this.zzerf = zzeek.zzaq(zzcgt.zzaa(this.zzene.zzelu));
        this.zzers = zzees.zzas(1, 0).zzas(zzcgo.zzamy()).zzbgo();
        this.zzert = zzeek.zzaq(zzcgu.zzm(this.zzerf, this.zzers, this.zzene.zzelk));
        this.zzeru = zzeek.zzaq(zzcgp.zzaf(this.zzert, zzdhi.zzasq()));
        this.zzeri = zzeek.zzaq(zzchp.zzag(this.zzene.zzemf, this.zzene.zzela));
        this.zzerv = zzchn.zzh(zzchc, this.zzeri, zzdhi.zzasq());
        this.zzerm = zzeek.zzaq(zzcln.zzaoa());
        this.zzerw = zzclo.zzaf(this.zzerm);
        this.zzerx = zzeek.zzaq(zzcld.zzan(this.zzerw, zzdhi.zzasq()));
        this.zzery = zzees.zzas(2, 2).zzat(this.zzerr).zzas(this.zzeru).zzat(this.zzerv).zzas(this.zzerx).zzbgo();
        this.zzerz = zzdin.zzap(this.zzery);
        this.zzesa = zzeek.zzaq(zzdio.zzs(zzdhi.zzasq(), this.zzene.zzeli, this.zzerz));
        this.zzfck = new zzcjm(this.zzene.zzelm);
        this.zzfcl = new zzctk(zzdhi.zzasq(), this.zzfck);
        this.zzelm = zzeek.zzaq(zzbpw.zza(zzbpt2, this.zzeqv));
        this.zzesj = zzcip.zzab(this.zzelm);
        this.zzesk = zzeek.zzaq(zzciq.zzaj(this.zzelm, this.zzesj));
        this.zzesl = zzeek.zzaq(zzcin.zzai(this.zzesa, this.zzelm));
        this.zzerc = zzdfs.zza(zzdfp2, this.zzeqq);
        this.zzeqr = zzdft.zzb(zzdfp2, this.zzeqq);
        this.zzeqs = zzbqa.zzm(zzbpt);
        this.zzeqt = zzeek.zzaq(zzbom.zzg(this.zzene.zzelk, this.zzeqr, this.zzeqs));
        this.zzequ = zzeek.zzaq(zzboo.zzd(this.zzene.zzelk, this.zzeqt));
        this.zzesm = zzbpy.zzb(zzbpt2, this.zzequ);
        this.zzesd = zzeek.zzaq(zzdfm.zzbc(this.zzeqv, this.zzeqr));
        this.zzemj = zzcuo.zzf(this.zzesm, this.zzene.zzelr, this.zzequ, this.zzesd, this.zzeqs);
        this.zzesn = zzcua.zzf(this.zzene.zzemi, this.zzeqs, this.zzeqv, this.zzene.zzemc);
        this.zzeso = zzcts.zzai(this.zzeqs);
        this.zzfcm = zzeek.zzaq(new zzctg(zzcta));
        this.zzesp = zzcwq.zzp(this.zzene.zzemg, this.zzeqv, this.zzfcm);
        this.zzest = zzcvr.zzau(this.zzelm, zzdhi.zzasq());
        this.zzesv = zzcub.zzaj(this.zzfcm);
        this.zzesw = zzbpv.zzi(zzbpt);
        this.zzesu = zzcwy.zzax(zzdhi.zzasq(), this.zzesw);
        this.zzesy = zzcvn.zzat(this.zzeqv, zzdhi.zzasq());
        this.zzesz = zzcwu.zzaw(this.zzesj, this.zzesk);
        this.zzeta = zzcxe.zzay(this.zzene.zzelm, this.zzeqp);
        this.zzeqz = zzeem.zzbf(zzdcu);
        this.zzetb = zzcxw.zzao(this.zzeqz);
        this.zzesx = zzcuf.zzaq(zzdhi.zzasq(), this.zzeqs);
        this.zzetc = zzcuy.zzas(zzdhi.zzasq(), this.zzeqv);
        this.zzete = zzeek.zzaq(zzcik.zzn(this.zzene.zzema, this.zzeqv, zzdhi.zzasq()));
        this.zzetf = zzctw.zzap(this.zzete, zzdhi.zzasq());
        this.zzetd = zzcxr.zzr(zzdhi.zzasq(), this.zzeqv, this.zzene.zzeln);
        this.zzeth = zzcyq.zzbb(zzdhi.zzasq(), this.zzeqv);
        this.zzetg = zzcvz.zzam(zzdhi.zzasq());
        this.zzeti = zzcxn.zzq(this.zzene.zzelx, zzdhi.zzasq(), this.zzeqv);
        this.zzetj = zzcvv.zzal(zzdhi.zzasq());
        this.zzetk = zzcwd.zzav(zzdhi.zzasq(), this.zzene.zzeml);
        this.zzetm = zzcuj.zzar(zzdhi.zzasq(), this.zzene.zzemc);
        this.zzfcn = zzeek.zzaq(new zzctd(zzcta));
        this.zzetn = zzeek.zzaq(zzcrr.zzah(this.zzene.zzell));
        this.zzetl = zzcxj.zza(zzdhi.zzasq(), this.zzene.zzeli, this.zzfcn, this.zzene.zzelp, this.zzelm, this.zzeqs, this.zzetn);
        this.zzeto = zzcuu.zzo(this.zzeqv, this.zzene.zzeli, zzdhi.zzasq());
        this.zzetq = zzcyc.zzaz(zzdhi.zzasq(), this.zzeqv);
        this.zzfco = zzeem.zzbf(zzdby);
        this.zzets = zzcvd.zzak(this.zzfco);
        this.zzetp = zzcwz.zzan(this.zzeqx);
        this.zzetu = zzees.zzas(28, 0).zzas(this.zzemj).zzas(this.zzesn).zzas(this.zzeso).zzas(this.zzesp).zzas(this.zzest).zzas(this.zzesv).zzas(this.zzesu).zzas(this.zzesy).zzas(this.zzesz).zzas(this.zzeta).zzas(this.zzetb).zzas(this.zzesx).zzas(this.zzetc).zzas(this.zzetf).zzas(this.zzetd).zzas(this.zzene.zzemi).zzas(this.zzeth).zzas(this.zzene.zzemk).zzas(this.zzetg).zzas(this.zzeti).zzas(this.zzetj).zzas(this.zzetk).zzas(this.zzetm).zzas(this.zzetl).zzas(this.zzeto).zzas(this.zzetq).zzas(this.zzets).zzas(this.zzetp).zzbgo();
        this.zzetv = zzcyi.zzba(zzdhi.zzasq(), this.zzetu);
        this.zzetw = zzbpo.zza(this.zzesa, this.zzene.zzeln, this.zzesj, this.zzeqw, zzcio.zzanl(), this.zzesk, this.zzesl, this.zzerc, this.zzeqx, this.zzetv);
        this.zzfcp = zzeek.zzaq(new zzctf(this.zzesa, this.zzfcl, this.zzetw));
    }

    public final zzdof<zzctj> zzafh() {
        return this.zzfcp.get();
    }

    /* synthetic */ zzbif(zzbhf zzbhf, zzcta zzcta, zzbog zzbog, zzchc zzchc, zzbpt zzbpt, zzdfp zzdfp, zzdcu zzdcu, zzdby zzdby, zzbhi zzbhi) {
        this(zzbhf, zzcta, zzbog, zzchc, zzbpt, zzdfp, (zzdcu) null, (zzdby) null);
    }
}
