package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

/* compiled from: com.google.android.gms:play-services-ads-lite@@19.0.1 */
public final class zzzx {
    public static final zzzi<String> zzcha = zzzi.zza(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzzi<String> zzchb = zzzi.zza(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    private static final zzaax<Boolean> zzchc = zzabk.zzchc;
    private static final zzzi<Integer> zzchd = zzzi.zza(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzzi<String> zzche = zzzi.zza(1, "gads:video_exo_player:version", "3");
    public static final zzzi<Integer> zzchf = zzzi.zza(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzzi<Integer> zzchg = zzzi.zza(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzzi<Integer> zzchh = zzzi.zza(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzzi<Integer> zzchi = zzzi.zza(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzzi<Integer> zzchj = zzzi.zza(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final zzzi<Integer> zzchk = zzzi.zza(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    public static final zzzi<String> zzchl = zzzi.zza(1, "gads:video_exo_player:precache_exceptions", "");
    public static final zzzi<Integer> zzchm = zzzi.zza(1, "gads:video_exo_player:min_retry_count", -1);
    public static final zzzi<Integer> zzchn = zzzi.zza(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzzi<Integer> zzcho = zzzi.zza(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzzi<Integer> zzchp = zzzi.zza(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzzi<Long> zzchq = zzzi.zzb(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzzi<Long> zzchr = zzzi.zzb(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzzi<Integer> zzchs = zzzi.zza(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzzi<String> zzcht = zzzi.zza(1, "gads:video:metric_frame_hash_times", "");
    public static final zzzi<Long> zzchu = zzzi.zzb(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzzi<Boolean> zzchv = zzzi.zza(1, "gads:video:force_watermark", (Boolean) false);
    public static final zzzi<Long> zzchw = zzzi.zzb(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzzi<Boolean> zzchx = zzzi.zza(1, "gads:video:spinner:enabled", (Boolean) false);
    public static final zzzi<Integer> zzchy = zzzi.zza(1, "gads:video:spinner:scale", 4);
    public static final zzzi<Long> zzchz = zzzi.zzb(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzzi<Boolean> zzcia = zzzi.zza(1, "gads:video:aggressive_media_codec_release", (Boolean) false);
    public static final zzzi<Boolean> zzcib = zzzi.zza(1, "gads:memory_bundle:debug_info", (Boolean) false);
    public static final zzzi<String> zzcic = zzzi.zza(1, "gads:video:codec_query_mime_types", "");
    public static final zzzi<Integer> zzcid = zzzi.zza(1, "gads:video:codec_query_minimum_version", 16);
    public static final zzzi<String> zzcie = zzzi.zza(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final zzzi<String> zzcif = zzzi.zza(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    public static final zzzi<String> zzcig = zzzi.zza(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    public static final zzzi<String> zzcih = zzzi.zza(1, "gad:mraid:version", "3.0");
    public static final zzzi<Boolean> zzcii = zzzi.zza(1, "gads:mraid:expanded_interstitial_fix", (Boolean) false);
    public static final zzzi<Boolean> zzcij = zzzi.zza(1, "gads:mraid:initial_size_fallback", (Boolean) false);
    public static final zzzi<Integer> zzcik = zzzi.zza(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzzi<Integer> zzcil = zzzi.zza(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzzi<Integer> zzcim = zzzi.zza(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzzi<String> zzcin = zzzi.zza(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzzi<String> zzcio = zzzi.zza(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzzi<Boolean> zzcip = zzzi.zza(1, "gads:content_fetch_disable_get_title_from_webview", (Boolean) false);
    public static final zzzi<Boolean> zzciq = zzzi.zza(1, "gads:content_fetch_enable_new_content_score", (Boolean) false);
    public static final zzzi<Boolean> zzcir = zzzi.zza(1, "gads:content_fetch_enable_serve_once", (Boolean) false);
    public static final zzzi<Boolean> zzcis = zzzi.zza(1, "gads:sai:enabled", (Boolean) true);
    public static final zzzi<String> zzcit = zzzi.zza(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzzi<String> zzciu = zzzi.zza(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
    public static final zzzi<Boolean> zzciv = zzzi.zza(1, "gads:sai:using_macro:enabled", (Boolean) false);
    public static final zzzi<String> zzciw = zzzi.zza(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzzi<Long> zzcix = zzzi.zzb(1, "gads:sai:timeout_ms", -1);
    public static final zzzi<Integer> zzciy = zzzi.zza(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzzi<Boolean> zzciz = zzzi.zza(1, "gads:sai:app_measurement_enabled3", (Boolean) false);
    public static final zzzi<Integer> zzcja = zzzi.zza(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
    public static final zzzi<Boolean> zzcjb = zzzi.zza(1, "gads:sai:force_through_reflection", (Boolean) true);
    public static final zzzi<Boolean> zzcjc = zzzi.zza(1, "gads:sai:gmscore_availability_check_disabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjd = zzzi.zza(1, "gads:sai:logging_disabled_for_drx", (Boolean) false);
    public static final zzzi<Boolean> zzcje = zzzi.zza(1, "gads:sai:inject_firebase_proxy", (Boolean) false);
    public static final zzzi<Boolean> zzcjf = zzzi.zza(1, "gads:sai:app_measurement_npa_enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjg = zzzi.zza(1, "gads:interstitial:app_must_be_foreground:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjh = zzzi.zza(1, "gads:interstitial:foreground_report:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcji = zzzi.zza(1, "gads:webview:error_web_response:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjj = zzzi.zza(1, "gads:webview:pause_interstitial:enabled", (Boolean) true);
    private static final zzzi<Boolean> zzcjk = zzzi.zza(1, "gads:rsku:webviewgone:kill_process:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjl = zzzi.zza(1, "gads:webviewgone:kill_process:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzcjm = zzzi.zza(1, "gads:rsku:webviewgone:new_onshow:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcjn = zzzi.zza(1, "gads:webviewgone:new_onshow:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjo = zzzi.zza(1, "gads:webview:pause_resume:enabled", (Boolean) true);
    private static final zzzi<Boolean> zzcjp = zzzi.zza(1, "gads:new_rewarded_ad:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcjq = zzzi.zza(1, "gads:rewarded:adapter_initialization_enabled", (Boolean) false);
    private static final zzzi<Long> zzcjr = zzzi.zzb(1, "gads:rewarded:adapter_timeout_ms", 20000);
    public static final zzzi<Boolean> zzcjs = zzzi.zza(1, "gads:rewarded:ad_metadata_enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcjt = zzzi.zza(1, "gads:rewarded:ssv_custom_data_enabled", (Boolean) true);
    public static final zzzi<Long> zzcju = zzzi.zzb(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzzi<Long> zzcjv = zzzi.zzb(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzzi<Boolean> zzcjw = zzzi.zza(1, "gads:adid_values_in_adrequest:enabled", (Boolean) false);
    public static final zzzi<Long> zzcjx = zzzi.zzb(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzzi<Boolean> zzcjy = zzzi.zza(1, "gads:disable_adid_values_in_ms", (Boolean) false);
    public static final zzzi<Long> zzcjz = zzzi.zzb(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final zzzi<Boolean> zzcka = zzzi.zza(1, "gads:custom_close_blocking:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzckb = zzzi.zza(1, "gads:disabling_closable_area:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzckc = zzzi.zza(1, "gads:use_system_ui_for_fullscreen:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzckd = zzzi.zza(1, "gads:ad_overlay:collect_cutout_info:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzcke = zzzi.zza(1, "gads:impression_optimization_enabled", (Boolean) false);
    private static final zzzi<String> zzckf = zzzi.zza(1, "gads:banner_ad_pool:schema", "customTargeting");
    private static final zzzi<Integer> zzckg = zzzi.zza(1, "gads:banner_ad_pool:max_queues", 3);
    private static final zzzi<Integer> zzckh = zzzi.zza(1, "gads:banner_ad_pool:max_pools", 3);
    public static final zzzi<Boolean> zzcki = zzzi.zza(1, "gads:delay_banner_renderer:enabled", (Boolean) true);
    private static final zzzi<Boolean> zzckj = zzzi.zza(1, "gads:interstitial_ad_pool:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzckk = zzzi.zza(1, "gads:interstitial_ad_pool:enabled_for_rewarded", (Boolean) false);
    private static final zzzi<String> zzckl = zzzi.zza(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    private static final zzzi<String> zzckm = zzzi.zza(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    private static final zzzi<Integer> zzckn = zzzi.zza(1, "gads:interstitial_ad_pool:max_pools", 3);
    private static final zzzi<Integer> zzcko = zzzi.zza(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    private static final zzzi<Integer> zzckp = zzzi.zza(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    private static final zzzi<String> zzckq = zzzi.zza(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    private static final zzzi<Integer> zzckr = zzzi.zza(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    private static final zzzi<Integer> zzcks = zzzi.zza(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    private static final zzzi<Long> zzckt = zzzi.zzb(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
    private static final zzzi<Long> zzcku = zzzi.zzb(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
    private static final zzzi<Float> zzckv = zzzi.zza(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
    private static final zzzi<Float> zzckw = zzzi.zza(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
    public static final zzzi<String> zzckx = zzzi.zza(1, "gads:spherical_video:vertex_shader", "");
    public static final zzzi<String> zzcky = zzzi.zza(1, "gads:spherical_video:fragment_shader", "");
    public static final zzzi<Boolean> zzckz = zzzi.zza(1, "gads:include_local_global_rectangles", (Boolean) false);
    public static final zzzi<Long> zzcla = zzzi.zzb(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzzi<Long> zzclb = zzzi.zzb(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    public static final zzzi<Boolean> zzclc = zzzi.zza(1, "gads:position_watcher:enable_scroll_aware_ads", (Boolean) false);
    public static final zzzi<Boolean> zzcld = zzzi.zza(1, "gads:position_watcher:send_scroll_data", (Boolean) false);
    private static final zzzi<Boolean> zzcle = zzzi.zza(1, "gads:gen204_signals:enabled", (Boolean) false);
    public static final zzzi<Long> zzclf = zzzi.zzb(1, "gads:rtb_v1_1:signal_timeout_ms", 1000);
    public static final zzzi<Boolean> zzclg = zzzi.zza(1, "gads:rtb_signal:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzclh = zzzi.zza(1, "gads:rtb_v1_1:cld:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcli = zzzi.zza(1, "gads:rtb_v1_1:cld:check_regex:enabled", (Boolean) true);
    public static final zzzi<String> zzclj = zzzi.zza(1, "gads:rtb_logging:regex", "(?!)");
    public static final zzzi<Boolean> zzclk = zzzi.zza(1, "gads:v1_1:adapter_initialization:enabled", (Boolean) true);
    public static final zzzi<Integer> zzcll = zzzi.zza(1, "gads:adapter_initialization:min_sdk_version", 15301000);
    public static final zzzi<Long> zzclm = zzzi.zzb(1, "gads:adapter_initialization:timeout", 30);
    public static final zzzi<Long> zzcln = zzzi.zzb(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final zzzi<Boolean> zzclo = zzzi.zza(1, "gads:initialization_csi:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzclp = zzzi.zza(1, "gads:initialization_csi_control:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzclq = zzzi.zza(1, "gads:gestures:clearTd:enabled", (Boolean) false);
    public static final zzaax<Boolean> zzclr = zzabl.zzcvd;
    public static final zzzi<Boolean> zzcls = zzzi.zza(1, "gads:gestures:errorlogging:enabled", (Boolean) false);
    public static final zzzi<Long> zzclt = zzzi.zzb(1, "gads:gestures:task_timeout", 2000);
    public static final zzzi<Boolean> zzclu = zzzi.zza(1, "gads:gestures:asig:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzclv = zzzi.zza(1, "gads:gestures:ans:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzclw = zzzi.zza(1, "gads:gestures:tos:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzclx = zzzi.zza(1, "gads:gestures:brt:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcly = zzzi.zza(1, "gads:gestures:fpi:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzclz = zzzi.zza(1, "gads:signal:app_permissions:disabled", (Boolean) false);
    public static final zzzi<Boolean> zzcma = zzzi.zza(1, "gads:gestures:inthex:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcmb = zzzi.zza(1, "gads:gestures:hpk:enabled", (Boolean) true);
    public static final zzzi<String> zzcmc = zzzi.zza(1, "gads:gestures:pk", "");
    public static final zzzi<Boolean> zzcmd = zzzi.zza(1, "gads:gestures:bs:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcme = zzzi.zza(1, "gads:gestures:check_initialization_thread:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcmf = zzzi.zza(1, "gads:gestures:get_query_in_non_ui_thread:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcmg = zzzi.zza(1, "gads:gestures:init_new_thread:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcmh = zzzi.zza(1, "gads:gestures:pds:enabled", (Boolean) true);
    private static final zzzi<Integer> zzcmi = zzzi.zza(1, "gads:gestures:as2percentage", 0);
    public static final zzzi<Boolean> zzcmj = zzzi.zza(1, "gads:gestures:las:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcmk = zzzi.zza(1, "gads:gestures:ns:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcml = zzzi.zza(1, "gads:gestures:vdd:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcmm = zzzi.zza(1, "gads:native:asset_view_touch_events", (Boolean) false);
    public static final zzzi<Boolean> zzcmn = zzzi.zza(1, "gads:native:set_touch_listener_on_asset_views", (Boolean) true);
    public static final zzzi<Boolean> zzcmo = zzzi.zza(1, "gads:ais:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcmp = zzzi.zza(1, "gads:send_available_disk_space:enabled", (Boolean) false);
    private static final zzzi<String> zzcmq;
    public static final zzzi<String> zzcmr = zzzi.zza(1, "gads:sdk_core_constants:caps", "");
    private static final zzzi<Boolean> zzcms = zzzi.zza(1, "gads:js_flags:disable_phenotype", (Boolean) false);
    public static final zzzi<String> zzcmt = zzzi.zza(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    private static final zzzi<String> zzcmu = zzzi.zza(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzzi<String> zzcmv = zzzi.zza(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzzi<Integer> zzcmw = zzzi.zza(1, "gads:native_video_load_timeout", 10);
    private static final zzzi<Integer> zzcmx = zzzi.zza(1, "gads:omid:native_webview_load_timeout", 2000);
    public static final zzzi<Boolean> zzcmy = zzzi.zza(1, "gads:enable_native_media_aspect_ratio", (Boolean) true);
    public static final zzzi<Boolean> zzcmz = zzzi.zza(1, "gads:native:media_content_main_image:enabled", (Boolean) true);
    public static final zzzi<String> zzcna = zzzi.zza(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    private static final zzzi<Boolean> zzcnb = zzzi.zza(1, "gads:enable_store_active_view_state", (Boolean) false);
    public static final zzzi<Boolean> zzcnc = zzzi.zza(1, "gads:enable_singleton_broadcast_receiver", (Boolean) false);
    public static final zzzi<Boolean> zzcnd = zzzi.zza(1, "gads:native:media_view_match_parent:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcne = zzzi.zza(1, "gads:native:count_impression_for_assets", (Boolean) false);
    private static final zzzi<Boolean> zzcnf = zzzi.zza(1, "gads:instream_ad:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcng = zzzi.zza(1, "gads:fluid_ad:use_wrap_content_height", (Boolean) false);
    private static final zzzi<Boolean> zzcnh = zzzi.zza(1, "gads:auto_location_for_coarse_permission", (Boolean) false);
    private static final zzzi<String> zzcni = zzzi.zzb(1, "gads:auto_location_for_coarse_permission:experiment_id");
    public static final zzzi<Long> zzcnj = zzzi.zzb(1, "gads:auto_location_timeout", 2000);
    private static final zzzi<String> zzcnk = zzzi.zzb(1, "gads:auto_location_timeout:experiment_id");
    private static final zzzi<Long> zzcnl = zzzi.zzb(1, "gads:auto_location_interval", -1);
    private static final zzzi<String> zzcnm = zzzi.zzb(1, "gads:auto_location_interval:experiment_id");
    public static final zzzi<Boolean> zzcnn = zzzi.zza(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcno = zzzi.zza(1, "gads:get_request_signals_cld:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcnp = zzzi.zza(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", (Boolean) true);
    public static final zzzi<Long> zzcnq = zzzi.zzb(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final zzzi<Long> zzcnr = zzzi.zzb(1, "gads:parental_controls:timeout", 2000);
    private static final zzzi<Integer> zzcns = zzzi.zza(1, "gads:cache:ad_request_timeout_millis", 250);
    private static final zzzi<Integer> zzcnt = zzzi.zza(1, "gads:cache:max_concurrent_downloads", 10);
    private static final zzzi<Long> zzcnu = zzzi.zzb(1, "gads:cache:javascript_timeout_millis", 5000);
    public static final zzzi<Boolean> zzcnv = zzzi.zza(1, "gads:cache:bind_on_foreground", (Boolean) false);
    public static final zzzi<Boolean> zzcnw = zzzi.zza(1, "gads:cache:bind_on_init", (Boolean) false);
    public static final zzzi<Boolean> zzcnx = zzzi.zza(1, "gads:cache:bind_on_request", (Boolean) false);
    public static final zzzi<Long> zzcny = zzzi.zzb(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzzi<Boolean> zzcnz = zzzi.zza(1, "gads:cache:use_cache_data_source", (Boolean) false);
    public static final zzzi<Boolean> zzcoa = zzzi.zza(1, "gads:cache:connection_per_read", (Boolean) false);
    public static final zzzi<Long> zzcob = zzzi.zzb(1, "gads:cache:connection_timeout", 5000);
    public static final zzzi<Long> zzcoc = zzzi.zzb(1, "gads:cache:read_only_connection_timeout", 5000);
    public static final zzzi<Boolean> zzcod = zzzi.zza(1, "gads:http_assets_cache:enabled", (Boolean) false);
    public static final zzzi<String> zzcoe = zzzi.zza(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzzi<Integer> zzcof = zzzi.zza(1, "gads:http_assets_cache:time_out", 100);
    public static final zzzi<Boolean> zzcog = zzzi.zza(1, "gads:chrome_custom_tabs_browser:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcoh = zzzi.zza(1, "gads:chrome_custom_tabs:disabled", (Boolean) false);
    public static final zzzi<Long> zzcoi = zzzi.zzb(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final zzzi<String> zzcoj = zzzi.zza(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzzi<String> zzcok = zzzi.zza(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzzi<String> zzcol = zzzi.zza(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzzi<String> zzcom = zzzi.zza(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzzi<Integer> zzcon = zzzi.zza(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzzi<Integer> zzcoo = zzzi.zza(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzzi<Boolean> zzcop = zzzi.zza(1, "gad:interstitial_for_multi_window", (Boolean) false);
    public static final zzzi<Boolean> zzcoq = zzzi.zza(1, "gad:interstitial_ad_stay_active_in_multi_window", (Boolean) false);
    public static final zzzi<Boolean> zzcor = zzzi.zza(1, "gad:interstitial_multi_window_method", (Boolean) false);
    public static final zzzi<Integer> zzcos = zzzi.zza(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzzi<Boolean> zzcot = zzzi.zza(1, "gads:clearcut_logging:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcou = zzzi.zza(1, "gads:clearcut_logging:write_to_file", (Boolean) false);
    public static final zzzi<Boolean> zzcov = zzzi.zza(1, "gad:publisher_testing:force_local_request:enabled", (Boolean) true);
    public static final zzzi<String> zzcow = zzzi.zza(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    public static final zzzi<String> zzcox = zzzi.zza(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    public static final zzzi<Integer> zzcoy = zzzi.zza(1, "gad:http_redirect_max_count:times", 8);
    public static final zzzi<Boolean> zzcoz = zzzi.zza(1, "gads:omid:enabled", (Boolean) true);
    public static final zzzi<Integer> zzcpa = zzzi.zza(1, "gads:omid:destroy_webview_delay", 1000);
    private static final zzzi<Boolean> zzcpb = zzzi.zza(1, "gads:nonagon:banner:enabled", (Boolean) false);
    private static final zzzi<String> zzcpc = zzzi.zza(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    private static final zzzi<Boolean> zzcpd = zzzi.zza(1, "gads:nonagon:app_open:enabled", (Boolean) true);
    public static final zzzi<Integer> zzcpe = zzzi.zza(1, "gads:app_open_beta:min_version", 99999999);
    private static final zzzi<String> zzcpf = zzzi.zza(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
    private static final zzzi<Boolean> zzcpg = zzzi.zza(1, "gads:nonagon:interstitial:enabled", (Boolean) false);
    private static final zzzi<String> zzcph = zzzi.zza(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    private static final zzzi<Boolean> zzcpi = zzzi.zza(1, "gads:nonagon:rewardedvideo:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcpj = zzzi.zza(1, "gads:nonagon:mobile_ads_setting_manager:enabled", (Boolean) false);
    public static final zzzi<String> zzcpk = zzzi.zza(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    private static final zzzi<Boolean> zzcpl = zzzi.zza(1, "gads:nonagon:nativead:enabled", (Boolean) false);
    private static final zzzi<String> zzcpm = zzzi.zza(1, "gads:nonagon:nativead:app_name", "(?!)");
    public static final zzzi<Boolean> zzcpn = zzzi.zza(1, "gads:nonagon:banner:check_dp_size", (Boolean) true);
    public static final zzzi<Boolean> zzcpo = zzzi.zza(1, "gads:nonagon:rewarded:load_multiple_ads", (Boolean) true);
    private static final zzzi<Boolean> zzcpp = zzzi.zza(1, "gads:nonagon:return_last_error_code", (Boolean) false);
    public static final zzzi<Boolean> zzcpq = zzzi.zza(1, "gads:nonagon:return_no_fill_error_code", (Boolean) false);
    public static final zzzi<Boolean> zzcpr = zzzi.zza(1, "gads:nonagon:continue_on_no_fill", (Boolean) false);
    private static final zzzi<Boolean> zzcps = zzzi.zza(1, "gads:nonagon:open_not_loaded_interstitial", (Boolean) true);
    public static final zzzi<Boolean> zzcpt = zzzi.zza(1, "gads:nonagon:separate_timeout:enabled", (Boolean) true);
    public static final zzzi<Integer> zzcpu = zzzi.zza(1, "gads:nonagon:request_timeout:seconds", 60);
    public static final zzzi<Boolean> zzcpv = zzzi.zza(1, "gads:nonagon:banner_recursive_renderer", (Boolean) false);
    public static final zzzi<Boolean> zzcpw = zzzi.zza(1, "gads:nonagon:app_stats_lock:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcpx = zzzi.zza(1, "gads:nonagon:app_stats_main_thread:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcpy = zzzi.zza(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcpz = zzzi.zza(1, "gads:active_view_gmsg_separate_pool:enabled", (Boolean) true);
    private static final zzzi<Boolean> zzcqa = zzzi.zza(1, "gads:nonagon:service:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcqb = zzzi.zza(1, "gads:nonagon:dpl_cancel_destroy_webview:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqc = zzzi.zza(1, "gads:signals:ad_id_info:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqd = zzzi.zza(1, "gads:signals:app_index:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqe = zzzi.zza(1, "gads:signals:attestation_token:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqf = zzzi.zza(1, "gads:signals:cache:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzcqg = zzzi.zza(1, "gads:signals:doritos:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqh = zzzi.zza(1, "gads:signals:doritos:v1:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzcqi = zzzi.zza(1, "gads:signals:doritos:v2:immediate:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqj = zzzi.zza(1, "gads:signals:location:enabled", (Boolean) false);
    private static final zzzi<Boolean> zzcqk = zzzi.zza(1, "gads:signals:network_prediction:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcql = zzzi.zza(1, "gads:signals:parental_control:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqm = zzzi.zza(1, "gads:signals:video_decoder:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqn = zzzi.zza(1, "gads:signals:signals_on_service:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcqo = zzzi.zza(1, "gads:attestation_token:enabled", (Boolean) false);
    public static final zzzi<Long> zzcqp = zzzi.zzb(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzzi<Integer> zzcqq = zzzi.zza(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzzi<Integer> zzcqr = zzzi.zza(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
    public static final zzzi<Integer> zzcqs = zzzi.zza(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
    public static final zzzi<Integer> zzcqt = zzzi.zza(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
    private static final zzaax<Boolean> zzcqu = zzabm.zzcve;
    public static final zzzi<Boolean> zzcqv = zzzi.zza(1, "gads:consent:shared_preference_reading:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcqw = zzzi.zza(1, "gads:consent:iab_consent_info:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcqx = zzzi.zza(1, "gads:fc_consent:shared_preference_reading:enabled", (Boolean) true);
    public static final zzzi<String> zzcqy = zzzi.zza(1, "gads:sp:json_string", "");
    public static final zzzi<Boolean> zzcqz = zzzi.zza(1, "gads:nativeads:image:sample:enabled", (Boolean) true);
    public static final zzzi<Integer> zzcra = zzzi.zza(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final zzzi<Boolean> zzcrb = zzzi.zza(1, "gads:nativeads:overlay_webview:onclick", (Boolean) false);
    public static final zzzi<Boolean> zzcrc = zzzi.zza(1, "gads:nativeads:create_overlay_webview:onjson", (Boolean) false);
    public static final zzzi<Boolean> zzcrd = zzzi.zza(1, "gads:nativeads:pub_image_scale_type:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcre = zzzi.zza(1, "gads:offline_signaling:enabled", (Boolean) false);
    public static final zzzi<Integer> zzcrf = zzzi.zza(1, "gads:offline_signaling:log_maximum", 100);
    public static final zzzi<Boolean> zzcrg = zzzi.zza(1, "gads:nativeads:template_signal:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcrh = zzzi.zza(1, "gads:nativeads:media_content_aspect_ratio:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcri = zzzi.zza(1, "gads:nativeads:media_content_metadata:enabled", (Boolean) true);
    public static final zzzi<Boolean> zzcrj = zzzi.zza(1, "gads:ar_ads:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcrk = zzzi.zza(1, "gads:precache_pool:verbose_logging", (Boolean) false);
    public static final zzzi<Integer> zzcrl = zzzi.zza(1, "gads:rewarded_precache_pool:count", 0);
    public static final zzzi<Integer> zzcrm = zzzi.zza(1, "gads:interstitial_precache_pool:count", 0);
    public static final zzzi<String> zzcrn = zzzi.zza(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
    public static final zzzi<String> zzcro = zzzi.zza(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
    public static final zzzi<String> zzcrp = zzzi.zza(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzzi<String> zzcrq = zzzi.zza(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzzi<Integer> zzcrr = zzzi.zza(1, "gads:rewarded_precache_pool:size", 1);
    public static final zzzi<Integer> zzcrs = zzzi.zza(1, "gads:interstitial_precache_pool:size", 1);
    public static final zzzi<Integer> zzcrt = zzzi.zza(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
    public static final zzzi<Integer> zzcru = zzzi.zza(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
    public static final zzzi<String> zzcrv = zzzi.zza(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzzi<String> zzcrw = zzzi.zza(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzzi<String> zzcrx = zzzi.zza(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzzi<String> zzcry = zzzi.zza(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
    public static final zzzi<Integer> zzcrz = zzzi.zza(1, "gads:app_open_precache_pool:count", 0);
    public static final zzzi<String> zzcsa = zzzi.zza(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzzi<Integer> zzcsb = zzzi.zza(1, "gads:app_open_precache_pool:size", 1);
    public static final zzzi<Integer> zzcsc = zzzi.zza(1, "gads:app_open_precache_pool:ad_time_limit", 14400);
    public static final zzzi<Boolean> zzcsd = zzzi.zza(1, "gads:memory_leak:b129558083", (Boolean) false);
    public static final zzzi<Boolean> zzcse = zzzi.zza(1, "gads:unhandled_event_reporting:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcsf = zzzi.zza(1, "gads:response_info:enabled", (Boolean) true);
    private static final zzzi<Boolean> zzcsg = zzzi.zza(1, "gads:signal_collection_without_rendering:enabled", (Boolean) true);
    private static final zzzi<Integer> zzcsh = zzzi.zza(1, "gads:signal_v2:min_version", 19677000);
    public static final zzzi<Boolean> zzcsi = zzzi.zza(1, "gads:paid_event_listener:enabled", (Boolean) false);
    public static final zzzi<Boolean> zzcsj = zzzi.zza(1, "gads:msa:experiments:enabled", (Boolean) false);

    public static void initialize(Context context) {
        zzayp.zza(new zzzw(context));
    }

    /* JADX WARNING: type inference failed for: r0v1, types: [com.google.android.gms.internal.ads.zzzr, com.google.android.gms.internal.ads.zzabz] */
    public static void zza(Context context, int i, JSONObject jSONObject) {
        zzvh.zzpb();
        SharedPreferences.Editor edit = context.getSharedPreferences("google_ads_flags", 0).edit();
        zzabd.zza(new zzzr(zzvh.zzpc(), edit, jSONObject));
        zzvh.zzpc().zza(edit, 1, jSONObject);
        zzvh.zzpb();
        edit.commit();
    }

    public static List<String> zzqj() {
        return zzvh.zzpc().zzqj();
    }

    public static List<String> zzqk() {
        return zzvh.zzpc().zzqk();
    }

    static {
        zzzi<String> zza = zzzi.zza(1, "gads:sdk_core_constants:experiment_id", (String) null);
        zzvh.zzpc().zzb(zza);
        zzcmq = zza;
    }
}
